server.port: 8081
datasource:
  url: jdbc:postgresql://localhost:5432/SchedulerService
  username: postgres
  password: password
  driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.PostgresSQLDialect
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
